FROM php:7.3-apache
RUN a2enmod rewrite
RUN docker-php-ext-install mysqli
RUN apt-get update && apt-get install -y \
    git \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng-dev \
    zlib1g-dev \
    libzip-dev \
    libicu-dev \
    g++
RUN docker-php-ext-install intl \
    && docker-php-ext-configure intl \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install zip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer require silverstripe/framework ~4.6 \
    && vendor/bin/sake installsake
