version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=SS_project
    volumes:
      - ./database:/var/lib/mysql
  php:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"